# Generated by Django 3.0 on 2020-01-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 1, 3, 21, 55, 32, 493263))),
            ],
        ),
    ]
