# Generated by Django 3.0 on 2020-01-04 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200104_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 19, 23, 7, 699866)),
        ),
    ]
