# Generated by Django 3.0.4 on 2020-04-17 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200418_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.UserIP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 8, 10, 999588)),
        ),
    ]
