# Generated by Django 3.0.4 on 2020-04-17 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20200418_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 20, 44, 367752)),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 20, 44, 368761)),
        ),
    ]
