# Generated by Django 3.0.4 on 2020-04-17 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20200418_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 37, 53, 737391)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 37, 53, 736346)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
