# Generated by Django 3.0.4 on 2020-04-17 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20200418_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ip',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 44, 22, 586693)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 2, 44, 22, 585466)),
        ),
    ]
