# Generated by Django 3.0.4 on 2020-04-17 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20200418_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 4, 5, 14, 932271)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 4, 5, 14, 931272)),
        ),
    ]
