# Generated by Django 3.0.4 on 2020-04-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20200418_0405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
    ]
