# Generated by Django 3.0.4 on 2020-04-17 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0013_auto_20200418_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 4, 18, 4, 22, 37, 414841))),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1000)),
                ('done', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 4, 18, 4, 22, 37, 414841))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.UserIP')),
            ],
        ),
    ]
